### ISSUE TITLE
Yarn build does not work. Yarn dev works.

### ISSUE THREAD

**Issue by techakilan** [emily-curry/snowpack-plugin-wasm-pack#1]
Thanks for the plugin.
I did the following,
1. yarn add --dev snowpack-plugin-wasm-pack
2. wasm-pack new mywasm
3.  in snowpack.config.js

inside module.exports and then inside plugins added
	[
	 'snowpack-plugin-wasm-pack',
	  {
	    projectPath: './mywasm',
	    profile:'release',
	  },
	],
4. in src/index.tsx
import init, { add } from 'mywasm';

const maths = async () => {
  await init();

  console.log('Addition in rust:', add(1, 2));
};
maths();
5.in tsconfig.json

{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": { "*": ["web_modules/.types/*"], "mywasm": ["./mywasm/pkg"] }
  }

yarn dev works like a charm as the dev server gets both index.js and index_bg.wasm files from ./mywasm/pkg. So importing index_bg.wasm from index.js works.
yarn build creates the build in ./dist folder. It does not work because  the index.js is in ./dist/assets folder and index_bg.wasm is in ./dist/dist/mywasm folder. The import 'index_bg.wasm' in index.js fails.

What am I doing wrong? How do I fix this?

Thanks

**Comment by emily-curry** [comment]
Hi there! I looked into this, and this appears to be just a snowpack config issue (in particular, without setting `root` or `mount` in your snowpack config, it will copy _everything_ in your base project dir to the build dir, which is likely what's tripping it up). However, the readme of this project wasn't a very good example of a minimum project, so I've updated the instructions in it. Would you run through those instructions again, and see if they get you a working project this time around? If not, you may post a link to a repo that demonstrates what you're seeing, and I can use that to look into it further.

**Comment by techakilan** [comment]
Hi, thanks for the reply.

Step to reproduce
1. git clone https://github.com/techakilan/solid-wasm-crm
2. cd solid-wasm-crm
3. yarn dev 
4. http://localhost:8080/ all works fine
5. yarn build
6. cd dist
7. python3 -m http.server
8. http://0.0.0.0:8000 does not load wasm file as expected and hence gives error

Thanks again

**Comment by emily-curry** [comment]
> https://github.com/techakilan/solid-wasm-crm  

This repository is not public.

**Comment by techakilan** [comment]
Hi,
I have added you as a collaborator so that you can view my configuration. Is that ok? 

Or please find attached the zipped master branch.
[solid-wasm-crm-master.zip](https://github.com/emily-curry/snowpack-plugin-wasm-pack/files/6991021/solid-wasm-crm-master.zip)

**Comment by emily-curry** [comment]
I've looked into your config, and the issue seems to be in how the snowpack `optimize.bundle` flag interacts with this plugin. In particular, this plugin sets a `mount` section with `static: true` for the wasm-pack output, which the snowpack docs indicate should mean that those files get written to the disk exactly as-is. However, that's not the behavior that's happening when `optimize.bundle` is true, the wasm-pack output is still getting included in the bundle, and the import paths are not being properly re-written. 

All that to say, disabling that flag seems to be the solution for now. Snowpack itself [does not yet recommend](https://www.snowpack.dev/guides/optimize-and-bundle) using the built-in optimize functionality, as it is new, and still recommends other solutions. And I am not certain if it is safe to have a bundler transform the wasm-pack output.

**Comment by techakilan** [comment]
Thank you, Emily. That resolved the build issue. I hope the snowpack team resolves the issue so that I am able to work with optimize.bundle set to true. 

Please raise this as an issue with the snowpack project.

Thanks again for your effort.

:+1:
